# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    {}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20        
    - run: go mod install


    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: go-mod-tidy-pr
      uses: sue445/go-mod-tidy-pr@v1.5.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        git_user_name: GitHub Actions
        git_user_email: john@boostchicken.dev
        reviewer: boostchicken
        base: main
